### ISSUE TITLE
Bugs in computation of P/R/F-measure

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#10]
Hello,

Precision and recall have strange behavior in some cases:

- Recall may exceed 100. This is because `n_overlaps` computes the number of times that a correct segment occurs in a prediction. If the correct segmentation is `dog @@s` and the model predicts `dog @@s @@s`, then the number of overlaps is 3, the number of correct segments is 2, and recall is 100 * 3 / 2 = 150.
- Precision and recall are insensitive to the order of returned segments. If the gold segmentation is `cat @@dog @@s` and the model predicts `cat @@s @@dog`, precision and recall are both computed as 100.

**Comment by kbatsuren** [comment]
Yes, it was the issue I was earlier talking about. Let me fix it as soon as possible. By the way, I have included the full baseline predictions of sentences.

**Comment by kbatsuren** [comment]
I will fix it today, and recompute the baseline results.

**Comment by kbatsuren** [comment]
I assume this problem is solved with this code. I will now push the code and insert small modifications to distinguish between word-level and sentence-level tasks.

![image](https://user-images.githubusercontent.com/50955407/161234075-982e8b70-bd06-4705-afb7-2bd357bc7d32.png)

**Comment by kbatsuren** [comment]
Let's close this issue. :) Thanks.
