### ISSUE TITLE
Baseline results in readme are incorrect

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#12]
Hello,

Various changes have been made to the evaluation script in recent weeks. However, the English results are from an old version of the script and slightly different results are obtained if one runs it now.

I have not checked whether the numbers are correct for other languages.

**Comment by kbatsuren** [comment]
Yes, that is true because the old-evaluation script incorrectly calculates `precision`, `recall`, and `f-measure`. Let me update them today.

**Comment by kbatsuren** [comment]
It is fixed.
