### ISSUE TITLE
Evaluation script is broken

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#13]
After the most recent round of changes, the evaluation script fails if the gold and guess sequences have a different number of tokens. This adds an implicit constraint on what kind of models can be used for the task, because not all models are guaranteed to produce the same number of tokens as are present in their input. This isn't just a theoretical issue: the new evaluation script fails on my strongest sentence-level seq2seq models.

As I understand it, the main advantage of the new way is that it is faster if the source and target scripts can be guaranteed to have the same number of tokens in each sentence. In my view, this does not outweigh the disadvantages.

The results for the two approaches are also slightly different, but I'm not sure if there's a good argument to be made for one approach over the other.

**Comment by kbatsuren** [comment]
The old version code has a bug as you know. The updated version won't evaluate every token separately instead it can evaluate as whole sentence.

**Comment by bpopeters** [comment]
I can do a PR in a few minutes, I've already implemented this for myself.
