### ISSUE TITLE
Use of unlabeled data

### ISSUE THREAD

**Issue by Waino** [sigmorphon/2022SegmentationST#15]
We are considering a semi-supervised training approach. However, the shared task only provides labeled training data, but does not mention unlabeled data.

Is it permissible in the shared task to use additional **unlabeled** data, more specifically a list of surface forms extracted from an additional corpus? If it is allowed to use unlabeled data, are there any preferences which corpora should be used, or can we choose freely?

**Comment by kbatsuren** [comment]
Hi @Waino,

Yes, if it is unlabeled data, you can use them as much as you want. The systems can compete separately in constrained and unconstrained settings.

**Comment by Waino** [comment]
Thank you @kbatsuren !
