### ISSUE TITLE
Interconnectedness of Part I and Part II

### ISSUE THREAD

**Issue by slvnwhrl** [sigmorphon/2022SegmentationST#16]
Hi,

I have a question regarding the interconnectedness of Part I and Part II of this shared task: Is it permissible to use a model for Part II that was previously trained for Part I?

Best

**Comment by kbatsuren** [comment]
Glad you asked this question. Yes, you can use this option. We won’t restrict it. :)

**Comment by slvnwhrl** [comment]
Thanks for clarifying @kbatsuren!
