### ISSUE TITLE
Etymology issues in English Sentence data

### ISSUE THREAD

**Issue by kbatsuren** [sigmorphon/2022SegmentationST#17]
OK. I mostly ask because I've found many incorrect segmentations in the English train and dev sets, some of them completely unreasonable. I was wondering if either

- They were not manually annotated
- They were manually annotated, but fell through the cracks of some noise filtering system

Some of the errors in the sentence-level data are pretty flagrant, such as
- not -> no @@t
- as -> a @@s

_Originally posted by @bpopeters in https://github.com/sigmorphon/2022SegmentationST/issues/6#issuecomment-1077713174_

**Comment by kbatsuren** [comment]
All the annotations are based on various editions of Wiktionary. These cases are exactly the issue that comes with Wiktionary. 

You can see [_as_](https://en.wiktionary.org/wiki/as#Etymology_3) --> a @@s
![image](https://user-images.githubusercontent.com/50955407/159966675-3585734e-52a5-46b2-a1d1-032952f3800b.png)

I am not saying these cases are right. For this shared task, we have spent some time manually excluding those cases. I think it is a good idea to briefly validate short words and regenerate `train` and `dev` sentence data for English. The sentence-level data for Czech and Mongolian are manually annotated from scratch, so the quality is high.

**Comment by kbatsuren** [comment]
Another case is `any`.

![image](https://user-images.githubusercontent.com/50955407/166517013-5e46ca78-f8c3-46e0-b84e-91e3021b2935.png)

**Comment by kbatsuren** [comment]
@bpopeters, This issue is fixed with the new update of English sentence data. :)

**Comment by bpopeters** [comment]
Oh, I didn't realize the data wasn't final yet.

**Comment by bpopeters** [comment]
Ok, thanks, great!
