### ISSUE TITLE
English and Czech test data part 2

### ISSUE THREAD

**Issue by slvnwhrl** [sigmorphon/2022SegmentationST#19]
While preparing the test data of part 2 for prediction, I realised that some of the English sentences start with a space as well as one Czech sentence (this sentence also contains two consecutive spaces at some point). I was wondering whether this intentional or a mistake (as it does not seem to happen in the dev or training data).

Thanks!

**Comment by kbatsuren** [comment]
`evaluation.py` code actually ignores the starting and ending spaces of sentences or in-between double spaces. So it would be fine.
