### ISSUE TITLE
The evaluation script overestimates levenshtein distance for non-ascii segment sequences

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#4]
Hello,

`evaluate_word.py` returns incorrect levenshtein distance results when the unsegmented word form contains non-ascii characters. For example, the baseline prediction for `débris` is `debris` and the script says that the levenshtein distance is 6 (it should be 1). I'm digging to try to find out why this is the case.

In the meantime, I also wrote a function from scratch to read the tsv files and compute the levenshtein distance. It does not make the same error as `evaluate_word.py`. So maybe it's better to just adapt this.

**Comment by kbatsuren** [comment]
Hi @bpopeters,

Yes, it is unacceptable mistake. Let me fix it as soon as possible. 

Thank you very much for finding such hidden mistake.

**Comment by bpopeters** [comment]
I've written some code that does levenshtein distance overall and for each category without having to compute everything twice (as the current code does) -- I could share that if it would be of interest.

**Comment by kbatsuren** [comment]
Definitely. If so, could you send the pull request? I can test it. :)

**Comment by bpopeters** [comment]
Will do tomorrow morning GMT.

**Comment by kbatsuren** [comment]
Again, thank you so much!

**Comment by bpopeters** [comment]
Still working on it: the precision/recall/f-measure results also seem to be incorrectly computed.
