### ISSUE TITLE
Data source and procedure

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#6]
Is there any information about how the datasets were created?

**Comment by kbatsuren** [comment]
Thanks for asking this question. 

The derivational and inflectional segmentations are described in UniMorph 4.0, which is under review of LREC 2022. Compound and root words were extracted from more than ten editions of Wiktionary (we did not describe it anywhere). I think we will describe them in the shared task paper. 

Could you leave me your email? so I can send you the UniMorph 4.0 paper

**Comment by bpopeters** [comment]
OK. I mostly ask because I've found many incorrect segmentations in the English train and dev sets, some of them completely unreasonable. I was wondering if either

- They were not manually annotated
- They were manually annotated, but fell through the cracks of some noise filtering system

Some of the errors in the sentence-level data are pretty flagrant, such as
- not -> no @@t
- as -> a @@s

**Comment by kbatsuren** [comment]
All the annotations are based on various editions of Wiktionary. These cases are exactly the issue that comes with Wiktionary. 

You can see _as_ --> a @@s
![image](https://user-images.githubusercontent.com/50955407/159966675-3585734e-52a5-46b2-a1d1-032952f3800b.png)

I am not saying these cases are right. For this shared task, we have spent some time manually excluding those cases. I think it is a good idea to briefly validate short words and regenerate `train` and `dev` sentence data for English. The sentence-level data for Czech and Mongolian are actually manually annotated from scratch, so the quality is high. 

Let me know what you think.

**Comment by kbatsuren** [comment]
So, it is hard for us to say the datasets are either manual annotations or not because word segmentations of Wiktionary are manual annotations.

**Comment by kbatsuren** [comment]
More about this issue, Wiktionarians annotate derivations, compounds, confixes in Etymology sections. In rare cases, we have these semantically-unrelated segmentations but they are etymologically correct.

**Comment by bpopeters** [comment]
I think it would be a good idea to validate the short words in the English sentences.

**Comment by kbatsuren** [comment]
Yes, I will validate them as soon as possible and release a new one by next Monday. Thank you very much for the deep analysis. :)

**Comment by kbatsuren** [comment]
@bpopeters I am sorry for the late fix of this issue.

**Comment by kbatsuren** [comment]
@bpopeters, the UniMorph 4.0 paper is online. https://arxiv.org/abs/2205.03608 From this paper, you can read the details of how segmentations have been developed from different editions of Wiktionary. :)
