### ISSUE TITLE
Sentence-level evaluation

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#7]
What evaluation metrics will be used for the sentence-level tasks? If they are the same as the word-level tasks, then more changes are needed for the evaluation script because it does not currently treat spaces as morpheme boundaries.

**Comment by bpopeters** [comment]
Come to think of it, whitespace should be treated as a word boundary for the word-level task as well.

**Comment by kbatsuren** [comment]
I do apologize for the horrible delay of the sentence-level evaluation metric!

Yes, I was thinking to reuse the same metric of word-level tasks, but I will let you know about this whitespace treat issue.

**Comment by kbatsuren** [comment]
> Come to think of it, whitespace should be treated as a word boundary for the word-level task as well.

Can I ask you why we need to do that for the word-level task? 

Actually, we should have removed the instances with whitespace. If you encountered those instances in `train` and `dev` word-level datasets, that is definitely our fault to fix.

**Comment by bpopeters** [comment]
`cut -f 1 eng.word.train.tsv | grep " "` produces 440 surface forms with spaces.

**Comment by bpopeters** [comment]
I don't necessarily think that whitespace is a problem in the word-level data because sometimes compound words **are** spelled with a space. But if this is the case, the evaluation script needs to account for it. This can be done with approximately 1 new line of code.

**Comment by kbatsuren** [comment]
During the dataset development, we used various filters to remove those compound words with spaces. Unfortunately, as you noticed, these instances are still in the datasets.

I was actually assuming that people would use the morpheme segmentation for already-tokenized words. So in this principle, it is a mistake to fix. 

What is convenient for you at this stage of participation? Should we remove them all or modify `evaluate_word.py` as you suggested?

**Comment by bpopeters** [comment]
> I was actually assuming that people would use the morpheme segmentation for already-tokenized words. So in this principle, it is a mistake to fix.

I'm not sure I understand what you mean.

> What is convenient for you at this stage of participation? Should we remove them all or modify `evaluate_word.py` as you suggested?

As a participant, I really don't know if it's appropriate to express too much opinion. However, I've already trained quite a few models with the current data and I would prefer not to throw them out. I've looked at the English and Spanish data (I don't speak any of the other task languages) and the English words mostly look like reasonable compounds, as well as derivations of proper nouns that have spaces in them (New Yorker, Costa Rican, New Dealism, etc.). On the other hand, the Spanish includes examples like

```
Audio (Peru)
Audio (Argentina)
Audio (Latin America)
Audio (Spain)
```

which seem like mistakes in the extraction pipeline.

Regarding `evaluate_word.py`, it seems that treating whitespace as a morpheme boundary would allow the same evaluation scripts to be used for sentence- and word-level tasks. That seems like a good thing to me.

**Comment by kbatsuren** [comment]
> ```
> Audio (Peru)
> Audio (Argentina)
> Audio (Latin America)
> Audio (Spain)
> ```
> 
> which seem like mistakes in the extraction pipeline.

Yes, I also encountered similar issues in other languages so I fixed them but didn't know Spanish has this type of mistake.

> 
> Regarding `evaluate_word.py`, it seems that treating whitespace as a morpheme boundary would allow the same evaluation scripts to be used for sentence- and word-level tasks. That seems like a good thing to me.

It sounds very good to me then. Could you send a pull request? :)

**Comment by kbatsuren** [comment]
I can ensure that for `test` datasets we won't have these types of problems mentioned here.

**Comment by simon-clematide** [comment]
BTW, it is irritating that in the examples in the README.md the tokens are not whitespace separated, while in the actual data all tokens are whitespace separated. Maybe the examples could be changed to look exactly as the real data looks like.

**Comment by kbatsuren** [comment]
Yes, you are right. I am really sorry for this inconvenience. Let me change it.

**Comment by kbatsuren** [comment]
I have mistakenly used the example sentences from the original proposal of the shared task. At the beginning of the task design, tokens aren't whitespace-separated then we decided to convert the original sentences to the current in order to safely compute the evaluation scores.

**Comment by kbatsuren** [comment]
I assume this issue is solved.
