### ISSUE TITLE
Spurious spacing in English sentence-level data

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2022SegmentationST#9]
Hello,

I've noticed that many examples in the English sentence data have either a trailing space in the surface string or a leading space in the segments. I have not observed the same thing for Czech or Mongolian, but have not checked rigorously.

**Comment by kbatsuren** [comment]
I am sorry for the delayed response. I will check the English sentence data immediately. Update you soon.

**Comment by kbatsuren** [comment]
Did you mean the spurious space before all sentences? I can fix that. Anyway, today or tomorrow, I will push all the baseline predictions and sentence-tool evaluation. Let me update it with them together.

Thank you very much for finding such mistake! :)

**Comment by bpopeters** [comment]
It looks like there's a spurious space right after the tab in each line.

**Comment by kbatsuren** [comment]
Yes. It is a systematic mistake. Thanks. It will be definitely fixed.

**Comment by kbatsuren** [comment]
I am sorry for delaying the codes and baseline results.

**Comment by kbatsuren** [comment]
I have just fixed this issue.
